# Generated by Django 5.0 on 2025-06-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DanceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("Jazz", "Jazz"),
                            ("Kpop", "Kpop"),
                            ("Hip-hop", "Hip-hop"),
                            ("House", "House"),
                            ("Urban", "Urban"),
                        ],
                        default="Jazz",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Basic",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="", null=True)),
                (
                    "schedule",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("max_students", models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("membership_number", models.CharField(max_length=20, unique=True)),
                ("classes_left", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                (
                    "dance_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.danceclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="studio.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "dance_class", "date")},
            },
        ),
    ]
